**Dataset Information**:                                                             
This is an educational data set which is collected from learning management system (LMS) called Kalboard 360. Kalboard 360 is a multi-agent LMS, which has been designed to facilitate learning through the use of leading-edge technology. Such system provides users with a synchronous access to educational resources from any device with Internet connection.

The data is collected using a learner activity tracker tool, which called experience API (xAPI). The xAPI is a component of the training and learning architecture (TLA) that enables to monitor learning progress and learner’s actions like reading an article or watching a training video. The experience API helps the learning activity providers to determine the learner, activity and objects that describe a learning experience. The dataset consists of 480 student records and 16 features. The features are classified into three major categories: (1) Demographic features such as gender and nationality. (2) Academic background features such as educational stage, grade Level and section. (3) Behavioral features such as raised hand on class, opening resources, answering survey by parents, and school satisfaction.

The dataset consists of 305 males and 175 females. The students come from different origins such as 179 students are from Kuwait, 172 students are from Jordan, 28 students from Palestine, 22 students are from Iraq, 17 students from Lebanon, 12 students from Tunis, 11 students from Saudi Arabia, 9 students from Egypt, 7 students from Syria, 6 students from USA, Iran and Libya, 4 students from Morocco and one student from Venezuela.

The dataset is collected through two educational semesters: 245 student records are collected during the first semester and 235 student records are collected during the second semester.

The data set includes also the school attendance feature such as the students are classified into two categories based on their absence days: 191 students exceed 7 absence days and 289 students their absence days under 7.

This dataset includes also a new category of features; this feature is parent parturition in the educational process. Parent participation feature have two sub features: Parent Answering Survey and Parent School Satisfaction. There are 270 of the parents answered survey and 210 are not, 292 of the parents are satisfied from the school and 188 are not.

**Attributes**                                                                         
1 Gender - student's gender (nominal: 'Male' or 'Female’)

2 Nationality- student's nationality (nominal:’ Kuwait’,’ Lebanon’,’ Egypt’,’ SaudiArabia’,’ USA’,’ Jordan’,’ Venezuela’,’ Iran’,’ Tunis’,’ Morocco’,’ Syria’,’ Palestine’,’ Iraq’,’ Lybia’)

3 Place of birth- student's Place of birth (nominal:’ Kuwait’,’ Lebanon’,’ Egypt’,’ SaudiArabia’,’ USA’,’ Jordan’,’ Venezuela’,’ Iran’,’ Tunis’,’ Morocco’,’ Syria’,’ Palestine’,’ Iraq’,’ Lybia’)

4 Educational Stages- educational level student belongs (nominal: ‘lowerlevel’,’MiddleSchool’,’HighSchool’)

5 Grade Levels- grade student belongs (nominal: ‘G-01’, ‘G-02’, ‘G-03’, ‘G-04’, ‘G-05’, ‘G-06’, ‘G-07’, ‘G-08’, ‘G-09’, ‘G-10’, ‘G-11’, ‘G-12 ‘)

6 Section ID- classroom student belongs (nominal:’A’,’B’,’C’)

7 Topic- course topic (nominal:’ English’,’ Spanish’, ‘French’,’ Arabic’,’ IT’,’ Math’,’ Chemistry’, ‘Biology’, ‘Science’,’ History’,’ Quran’,’ Geology’)

8 Semester- school year semester (nominal:’ First’,’ Second’)

9 Parent responsible for student (nominal:’mom’,’father’)

10 Raised hand- how many times the student raises his/her hand on classroom (numeric:0-100)

11- Visited resources- how many times the student visits a course content(numeric:0-100)

12 Viewing announcements-how many times the student checks the new announcements(numeric:0-100)

13 Discussion groups- how many times the student participate on discussion groups (numeric:0-100)

14 Parent Answering Survey- parent answered the surveys which are provided from school or not (nominal:’Yes’,’No’)

15 Parent School Satisfaction- the Degree of parent satisfaction from school(nominal:’Yes’,’No’)

16 Student Absence Days-the number of absence days for each student (nominal: above-7, under-7)

**The students are classified into three numerical intervals based on their total grade/mark:**                      
Low-Level: interval includes values from 0 to 69,

Middle-Level: interval includes values from 70 to 89,

High-Level: interval includes values from 90-100.

In [77]:
import numpy as np
import pandas as pd
import pandas_profiling
import scipy.stats
import warnings
warnings.filterwarnings('ignore')

In [2]:
from scipy.stats import chi2_contingency

In [3]:
data=pd.read_csv('Dataset.csv')

In [4]:
pandas_profiling.ProfileReport(data)

Above overview of the dataset shows that there is no missing values in the dataset.
There are 17 attributes : Demographic(3), Academic (5), Behavioral(8)


In [5]:
data.dtypes

gender                      object
NationalITy                 object
PlaceofBirth                object
StageID                     object
GradeID                     object
SectionID                   object
Topic                       object
Semester                    object
Relation                    object
raisedhands                  int64
VisITedResources             int64
AnnouncementsView            int64
Discussion                   int64
ParentAnsweringSurvey       object
ParentschoolSatisfaction    object
StudentAbsenceDays          object
Class                       object
dtype: object

# EDA

In [6]:
data['gender'].value_counts(normalize=True)   

M    0.635417
F    0.364583
Name: gender, dtype: float64

Around 63% of the students in training data are male and 36% are female

In [7]:
data['NationalITy'].value_counts()

KW             179
Jordan         172
Palestine       28
Iraq            22
lebanon         17
Tunis           12
SaudiArabia     11
Egypt            9
Syria            7
Lybia            6
USA              6
Iran             6
Morocco          4
venzuela         1
Name: NationalITy, dtype: int64

In [8]:
data['PlaceofBirth'].value_counts()

KuwaIT         180
Jordan         176
Iraq            22
lebanon         19
SaudiArabia     16
USA             16
Palestine       10
Tunis            9
Egypt            9
Syria            6
Lybia            6
Iran             6
Morocco          4
venzuela         1
Name: PlaceofBirth, dtype: int64

There are some people whose place of birth and nationality is not same

In [9]:
pd.crosstab(data['gender'],data['Class'],normalize='all')

Class          H         L         M
gender                              
F       0.156250  0.050000  0.158333
M       0.139583  0.214583  0.281250

In [10]:
data.groupby(['gender','NationalITy','PlaceofBirth'])['Class'].count().plot(kind='barh')

In [11]:
aa=data.groupby(['gender','NationalITy','PlaceofBirth'])['Class'].count()
print(aa)

gender  NationalITy  PlaceofBirth
F       Egypt        Egypt             2
        Iran         Iran              1
        Iraq         Iraq              6
        Jordan       Egypt             1
                     Jordan           71
                     KuwaIT            1
                     Palestine         2
                     USA               1
                     lebanon           3
        KW           KuwaIT           52
                     USA               2
        Lybia        Lybia             2
        Morocco      Morocco           1
        Palestine    Jordan            6
                     Palestine         2
        SaudiArabia  SaudiArabia       3
                     USA               1
        Syria        Syria             2
        Tunis        USA               1
        USA          USA               4
        lebanon      lebanon          11
M       Egypt        Egypt             6
                     KuwaIT            1
        Iran         Ir

In [12]:
pd.crosstab(data['gender'],data['Class'],normalize='columns')

Class          H         L        M
gender                             
F       0.528169  0.188976  0.36019
M       0.471831  0.811024  0.63981

In [13]:
pd.crosstab(data['gender'],data['Class'],normalize='index')

Class          H         L         M
gender                              
F       0.428571  0.137143  0.434286
M       0.219672  0.337705  0.442623

43.4% of the females are in middle level and 44.2% of the males are in middle level

In [14]:
pd.crosstab(data['gender'],data['Class'])

Class    H    L    M
gender              
F       75   24   76
M       67  103  135

In [15]:
data.groupby(['gender','NationalITy','PlaceofBirth'])['Class'].count()

gender  NationalITy  PlaceofBirth
F       Egypt        Egypt             2
        Iran         Iran              1
        Iraq         Iraq              6
        Jordan       Egypt             1
                     Jordan           71
                     KuwaIT            1
                     Palestine         2
                     USA               1
                     lebanon           3
        KW           KuwaIT           52
                     USA               2
        Lybia        Lybia             2
        Morocco      Morocco           1
        Palestine    Jordan            6
                     Palestine         2
        SaudiArabia  SaudiArabia       3
                     USA               1
        Syria        Syria             2
        Tunis        USA               1
        USA          USA               4
        lebanon      lebanon          11
M       Egypt        Egypt             6
                     KuwaIT            1
        Iran         Ir

In [16]:
chi2_contingency(pd.crosstab(data['StageID'],data['Class']))

(7.098963112154691,
 0.13074998727949977,
 4,
 array([[  9.7625    ,   8.73125   ,  14.50625   ],
        [ 73.36666667,  65.61666667, 109.01666667],
        [ 58.87083333,  52.65208333,  87.47708333]]))

p-value : 0.13

In [17]:
chi2_contingency(pd.crosstab(data['Semester'],data['Class']))

(7.821648437009264,
 0.02002399011511543,
 2,
 array([[ 72.47916667,  64.82291667, 107.69791667],
        [ 69.52083333,  62.17708333, 103.30208333]]))

p-value : 0.02

In [18]:
chi2_contingency(pd.crosstab(data['GradeID'],data['Class']))

(29.01313265749282,
 0.04821879926548518,
 18,
 array([[43.4875    , 38.89375   , 64.61875   ],
        [14.2       , 12.7       , 21.1       ],
        [ 0.8875    ,  0.79375   ,  1.31875   ],
        [ 9.46666667,  8.46666667, 14.06666667],
        [29.87916667, 26.72291667, 44.39791667],
        [34.31666667, 30.69166667, 50.99166667],
        [ 1.47916667,  1.32291667,  2.19791667],
        [ 1.18333333,  1.05833333,  1.75833333],
        [ 3.84583333,  3.43958333,  5.71458333],
        [ 3.25416667,  2.91041667,  4.83541667]]))

p-value : 0.048

In [19]:
chi2_contingency(pd.crosstab(data['NationalITy'],data['Class']))

(73.84032005687038,
 1.802272458215712e-06,
 26,
 array([[ 2.6625    ,  2.38125   ,  3.95625   ],
        [ 1.775     ,  1.5875    ,  2.6375    ],
        [ 6.50833333,  5.82083333,  9.67083333],
        [50.88333333, 45.50833333, 75.60833333],
        [52.95416667, 47.36041667, 78.68541667],
        [ 1.775     ,  1.5875    ,  2.6375    ],
        [ 1.18333333,  1.05833333,  1.75833333],
        [ 8.28333333,  7.40833333, 12.30833333],
        [ 3.25416667,  2.91041667,  4.83541667],
        [ 2.07083333,  1.85208333,  3.07708333],
        [ 3.55      ,  3.175     ,  5.275     ],
        [ 1.775     ,  1.5875    ,  2.6375    ],
        [ 5.02916667,  4.49791667,  7.47291667],
        [ 0.29583333,  0.26458333,  0.43958333]]))

p-value : 1.80

In [20]:
chi2_contingency(pd.crosstab(data['Relation'],data['Class']))

(81.3655417695057,
 2.1463329668513236e-18,
 2,
 array([[ 83.72083333,  74.87708333, 124.40208333],
        [ 58.27916667,  52.12291667,  86.59791667]]))

p-value : 2.14

In [21]:
chi2_contingency(pd.crosstab(data['SectionID'],data['Class']))

(4.439408551458438,
 0.34979263894626117,
 4,
 array([[ 83.72083333,  74.87708333, 124.40208333],
        [ 49.40416667,  44.18541667,  73.41041667],
        [  8.875     ,   7.9375    ,  13.1875    ]]))

p-value : 0.34

In [22]:
chi2_contingency(pd.crosstab(data['Topic'],data['Class']))

(45.173869837330855,
 0.0025222672882491857,
 22,
 array([[17.45416667, 15.61041667, 25.93541667],
        [ 8.875     ,  7.9375    , 13.1875    ],
        [ 7.1       ,  6.35      , 10.55      ],
        [13.3125    , 11.90625   , 19.78125   ],
        [19.22916667, 17.19791667, 28.57291667],
        [ 7.1       ,  6.35      , 10.55      ],
        [ 5.62083333,  5.02708333,  8.35208333],
        [28.10416667, 25.13541667, 41.76041667],
        [ 6.2125    ,  5.55625   ,  9.23125   ],
        [ 6.50833333,  5.82083333,  9.67083333],
        [15.0875    , 13.49375   , 22.41875   ],
        [ 7.39583333,  6.61458333, 10.98958333]]))

p-value : 0.002

In [23]:
chi2_contingency(pd.crosstab(data['gender'],data['Class']))

(33.326236065889375,
 5.79828805474192e-08,
 2,
 array([[ 51.77083333,  46.30208333,  76.92708333],
        [ 90.22916667,  80.69791667, 134.07291667]]))

p-value : 5.79

In [24]:
chi2_contingency(pd.crosstab(data['StageID'],data['Class']))

(7.098963112154691,
 0.13074998727949977,
 4,
 array([[  9.7625    ,   8.73125   ,  14.50625   ],
        [ 73.36666667,  65.61666667, 109.01666667],
        [ 58.87083333,  52.65208333,  87.47708333]]))

p-value : 0.13

**Variables that are giving p values less than 0.05 are Semester, GradeID ,Topic which mean these have strong correlation with Class**

In [25]:
data['StageID'].value_counts(normalize=True)   

MiddleSchool    0.516667
lowerlevel      0.414583
HighSchool      0.068750
Name: StageID, dtype: float64

Around 51% of the students belong to the Middle School.                                      
Around 41% of the students belong to the Lower School.                                       
Around 6% of the students belong to the High School.

In [26]:
pd.crosstab(data['Class'],data['Semester'],normalize='columns')

Semester         F         S
Class                       
H         0.253061  0.340426
L         0.314286  0.212766
M         0.432653  0.446809

In [27]:
pd.crosstab(data['Class'],data['GradeID'],normalize='columns')

GradeID      G-02      G-04  G-05    G-06      G-07      G-08  G-09  G-10  \
Class                                                                       
H        0.278912  0.291667   0.0  0.4375  0.287129  0.284483   0.0  0.25   
L        0.340136  0.229167   1.0  0.0625  0.277228  0.215517   0.2  0.25   
M        0.380952  0.479167   0.0  0.5000  0.435644  0.500000   0.8  0.50   

GradeID      G-11      G-12  
Class                        
H        0.461538  0.363636  
L        0.153846  0.363636  
M        0.384615  0.272727

In [28]:
pd.crosstab(data['Class'],data['Topic'])

Topic  Arabic  Biology  Chemistry  English  French  Geology  History  IT  \
Class                                                                      
H          19       16         10       17      20        6        4  15   
L          17        4          8       10      16        0        3  38   
M          23       10          6       18      29       18       12  42   

Topic  Math  Quran  Science  Spanish  
Class                                 
H         6      8       16        5  
L         7      6       10        8  
M         8      8       25       12

In [29]:
pd.crosstab(data['Class'],data['Topic'],normalize='columns')

Topic    Arabic   Biology  Chemistry   English    French  Geology   History  \
Class                                                                         
H      0.322034  0.533333   0.416667  0.377778  0.307692     0.25  0.210526   
L      0.288136  0.133333   0.333333  0.222222  0.246154     0.00  0.157895   
M      0.389831  0.333333   0.250000  0.400000  0.446154     0.75  0.631579   

Topic        IT      Math     Quran   Science  Spanish  
Class                                                   
H      0.157895  0.285714  0.363636  0.313725     0.20  
L      0.400000  0.333333  0.272727  0.196078     0.32  
M      0.442105  0.380952  0.363636  0.490196     0.48

In [30]:
data['StudentAbsenceDays'].value_counts(normalize=True)

Under-7    0.602083
Above-7    0.397917
Name: StudentAbsenceDays, dtype: float64

In [31]:
pd.crosstab(data['Class'],data['StudentAbsenceDays'])

StudentAbsenceDays  Above-7  Under-7
Class                               
H                         4      138
L                       116       11
M                        71      140

In [32]:
pd.crosstab(data['Class'],data['StudentAbsenceDays'],normalize='columns')

StudentAbsenceDays   Above-7   Under-7
Class                                 
H                   0.020942  0.477509
L                   0.607330  0.038062
M                   0.371728  0.484429

In [33]:
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [34]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

In [35]:
le=LabelEncoder()

In [36]:
cat_var = []
num_var = []
for col in data.columns:
    if data[col].dtypes == 'O':   #i.e. if it is an OBJECT
        cat_var.append(col)
    else:
        num_var.append(col)
        #continue

In [37]:
cat_var

['gender',
 'NationalITy',
 'PlaceofBirth',
 'StageID',
 'GradeID',
 'SectionID',
 'Topic',
 'Semester',
 'Relation',
 'ParentAnsweringSurvey',
 'ParentschoolSatisfaction',
 'StudentAbsenceDays',
 'Class']

In [38]:
num_var

['raisedhands', 'VisITedResources', 'AnnouncementsView', 'Discussion']

In [39]:
data_cat = data[cat_var]
data_num = data[num_var]

In [40]:
xx = data_cat.apply(lambda x: le.fit_transform(x), axis=0)

In [41]:
xx.dtypes

gender                      int64
NationalITy                 int64
PlaceofBirth                int64
StageID                     int64
GradeID                     int64
SectionID                   int64
Topic                       int64
Semester                    int64
Relation                    int64
ParentAnsweringSurvey       int64
ParentschoolSatisfaction    int64
StudentAbsenceDays          int64
Class                       int64
dtype: object

In [42]:
xx.head()

gender  NationalITy  PlaceofBirth  StageID  GradeID  SectionID  Topic  \
0       1            4             4        2        1          0      7   
1       1            4             4        2        1          0      7   
2       1            4             4        2        1          0      7   
3       1            4             4        2        1          0      7   
4       1            4             4        2        1          0      7   

   Semester  Relation  ParentAnsweringSurvey  ParentschoolSatisfaction  \
0         0         0                      1                         1   
1         0         0                      1                         1   
2         0         0                      0                         0   
3         0         0                      0                         0   
4         0         0                      0                         0   

   StudentAbsenceDays  Class  
0                   1      2  
1                   1      2  
2                   0      1  
3                   0      1  
4                   0      2

In [43]:
x1=xx.iloc[:,:12]
x1.head()

gender  NationalITy  PlaceofBirth  StageID  GradeID  SectionID  Topic  \
0       1            4             4        2        1          0      7   
1       1            4             4        2        1          0      7   
2       1            4             4        2        1          0      7   
3       1            4             4        2        1          0      7   
4       1            4             4        2        1          0      7   

   Semester  Relation  ParentAnsweringSurvey  ParentschoolSatisfaction  \
0         0         0                      1                         1   
1         0         0                      1                         1   
2         0         0                      0                         0   
3         0         0                      0                         0   
4         0         0                      0                         0   

   StudentAbsenceDays  
0                   1  
1                   1  
2                   0  
3                   0  
4                   0

In [44]:
y1=pd.DataFrame(xx['Class'])
y1.head()

Class
0      2
1      2
2      1
3      1
4      2

In [45]:
data_encoded=pd.concat([x1,data_num],axis=1)
data_encoded.head()

gender  NationalITy  PlaceofBirth  StageID  GradeID  SectionID  Topic  \
0       1            4             4        2        1          0      7   
1       1            4             4        2        1          0      7   
2       1            4             4        2        1          0      7   
3       1            4             4        2        1          0      7   
4       1            4             4        2        1          0      7   

   Semester  Relation  ParentAnsweringSurvey  ParentschoolSatisfaction  \
0         0         0                      1                         1   
1         0         0                      1                         1   
2         0         0                      0                         0   
3         0         0                      0                         0   
4         0         0                      0                         0   

   StudentAbsenceDays  raisedhands  VisITedResources  AnnouncementsView  \
0                   1           15                16                  2   
1                   1           20                20                  3   
2                   0           10                 7                  0   
3                   0           30                25                  5   
4                   0           40                50                 12   

   Discussion  
0          20  
1          25  
2          30  
3          35  
4          50

In [46]:
corr=data.corr()
corr

raisedhands  VisITedResources  AnnouncementsView  \
raisedhands           1.000000          0.691572           0.643918   
VisITedResources      0.691572          1.000000           0.594500   
AnnouncementsView     0.643918          0.594500           1.000000   
Discussion            0.339386          0.243292           0.417290   

                   Discussion  
raisedhands          0.339386  
VisITedResources     0.243292  
AnnouncementsView    0.417290  
Discussion           1.000000

In [47]:
from sklearn.model_selection import train_test_split

In [48]:
X_train,X_test,y_train,y_test=train_test_split(data_encoded,y1,test_size=0.2,random_state=123)       #Splitting the dataset into training and testing data

In [49]:
print(X_train.shape)
X_train.head()

(384, 16)


gender  NationalITy  PlaceofBirth  StageID  GradeID  SectionID  Topic  \
282       0            3             3        1        3          0      3   
274       0           12            12        1        3          0      3   
131       1            3             3        2        0          2      7   
345       0            3             3        2        0          1      4   
20        0            4             4        1        4          0      7   

     Semester  Relation  ParentAnsweringSurvey  ParentschoolSatisfaction  \
282         0         1                      0                         1   
274         0         1                      1                         1   
131         0         0                      1                         1   
345         0         1                      0                         1   
20          0         0                      0                         0   

     StudentAbsenceDays  raisedhands  VisITedResources  AnnouncementsView  \
282                   1           95                94                 72   
274                   1           95                82                 82   
131                   1           80                42                 20   
345                   1           13                82                 20   
20                    0           60                60                 33   

     Discussion  
282          80  
274          70  
131          50  
345          30  
20           90

In [50]:
print(X_test.shape)
X_test.head()

(96, 16)


gender  NationalITy  PlaceofBirth  StageID  GradeID  SectionID  Topic  \
422       0            3             3        1        5          0      5   
279       1            7             3        1        3          0      3   
5         0            4             4        2        1          0      7   
299       1            3             3        2        1          0     10   
398       1            7             7        1        4          0      1   

     Semester  Relation  ParentAnsweringSurvey  ParentschoolSatisfaction  \
422         0         1                      1                         1   
279         1         1                      0                         1   
5           0         0                      1                         0   
299         1         0                      0                         1   
398         0         0                      1                         1   

     StudentAbsenceDays  raisedhands  VisITedResources  AnnouncementsView  \
422                   0           70                69                 46   
279                   1           72                41                 46   
5                     0           42                30                 13   
299                   0           32                14                 32   
398                   1           88                90                 86   

     Discussion  
422          45  
279          27  
5            70  
299          29  
398          81

In [51]:
print(y_train.shape)
y_train.head()

(384, 1)


Class
282      0
274      0
131      2
345      0
20       2

In [52]:
print(y_test.shape)
y_test.head()

(96, 1)


Class
422      2
279      2
5        2
299      2
398      0

In [53]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import AdaBoostClassifier,BaggingClassifier,RandomForestClassifier
from sklearn.metrics import cohen_kappa_score

In [54]:
from sklearn.metrics import make_scorer
def kappa(y,y_pred,**kargs):
    return cohen_kappa_score(y,y_pred)

kappa=make_scorer(kappa)

In [55]:
tree=DecisionTreeClassifier()
rf=RandomForestClassifier()
bagg=BaggingClassifier(base_estimator=tree)
boost=AdaBoostClassifier(base_estimator=tree)

In [56]:
param_grid_tree={'criterion':['gini','entropy'],'max_depth':[3,5,7,9]}
param_grid_rf={'n_estimators':[50,100,200],'max_depth':[3,5,7,9]}
param_grid_bagg={'n_estimators':[50,100,200]}
param_grid_boost={'n_estimators':[50,100,200],'learning_rate':[0.0001,0.0003,0.0005]}

In [57]:
best_model_tree=GridSearchCV(estimator=tree,param_grid=param_grid_tree,scoring=kappa,cv=5)
best_model_rf=GridSearchCV(estimator=rf,param_grid=param_grid_rf,scoring=kappa,n_jobs=1,cv=5)
best_model_bagg=GridSearchCV(estimator=bagg,param_grid=param_grid_bagg,scoring=kappa,cv=5)
best_model_boost=GridSearchCV(estimator=boost,param_grid=param_grid_boost,scoring=kappa,cv=5)

In [58]:
best_model_tree.fit(X=X_train,y=y_train)

GridSearchCV(cv=5, error_score='raise',
       estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best'),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'criterion': ['gini', 'entropy'], 'max_depth': [3, 5, 7, 9]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=make_scorer(kappa), verbose=0)

In [59]:
best_model_tree.best_params_

{'criterion': 'gini', 'max_depth': 5}

In [60]:
cross_val_score(best_model_tree.best_estimator_,X=X_train,y=y_train,cv=5)

array([0.70512821, 0.71428571, 0.75324675, 0.72368421, 0.68421053])

In [61]:
cross_val_score(best_model_tree.best_estimator_,X=X_train,y=y_train,cv=5).mean()

0.713513679303153

In [78]:
best_model_rf.fit(X=X_train,y=y_train)

GridSearchCV(cv=5, error_score='raise',
       estimator=RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'n_estimators': [50, 100, 200], 'max_depth': [3, 5, 7, 9]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=make_scorer(kappa), verbose=0)

In [79]:
cross_val_score(best_model_rf.best_estimator_,X=X_train,y=y_train,cv=5)

array([0.73076923, 0.68831169, 0.75324675, 0.77631579, 0.71052632])

In [80]:
cross_val_score(best_model_rf.best_estimator_,X=X_train,y=y_train,cv=5).mean()

0.7524790998475209

In [81]:
best_model_rf.best_params_

{'max_depth': 7, 'n_estimators': 50}

In [82]:
best_model_bagg.fit(X=X_train,y=y_train)

GridSearchCV(cv=5, error_score='raise',
       estimator=BaggingClassifier(base_estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            ...n_estimators=10, n_jobs=1, oob_score=False,
         random_state=None, verbose=0, warm_start=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'n_estimators': [50, 100, 200]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=make_scorer(kappa), verbose=0)

In [83]:
cross_val_score(best_model_bagg.best_estimator_,X=X_train,y=y_train,cv=5)

array([0.75641026, 0.71428571, 0.75324675, 0.75      , 0.72368421])

In [84]:
cross_val_score(best_model_bagg.best_estimator_,X=X_train,y=y_train,cv=5).mean()

0.7525132761974868

In [85]:
best_model_bagg.best_params_

{'n_estimators': 200}

In [86]:
best_model_boost.fit(X=X_train,y=y_train)

GridSearchCV(cv=5, error_score='raise',
       estimator=AdaBoostClassifier(algorithm='SAMME.R',
          base_estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best'),
          learning_rate=1.0, n_estimators=50, random_state=None),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'n_estimators': [50, 100, 200], 'learning_rate': [0.0001, 0.0003, 0.0005]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=make_scorer(kappa), verbose=0)

In [87]:
best_model_boost.best_params_

{'learning_rate': 0.0005, 'n_estimators': 200}

In [88]:
cross_val_score(best_model_boost.best_estimator_,X=X_train,y=y_train,cv=5)

array([0.70512821, 0.66233766, 0.72727273, 0.73684211, 0.63157895])

In [89]:
cross_val_score(best_model_boost.best_estimator_,X=X_train,y=y_train,cv=5).mean()

0.6771482903061851

** Highest accuracy obtained in bagging model**

In [90]:
y_pred=best_model_bagg.predict(X_test)
y_pred

array([2, 2, 2, 1, 0, 2, 2, 2, 1, 1, 1, 1, 2, 1, 2, 0, 0, 0, 2, 1, 1, 1,
       1, 1, 0, 2, 1, 2, 1, 2, 2, 1, 1, 2, 0, 0, 2, 0, 2, 2, 2, 1, 0, 1,
       0, 0, 1, 1, 0, 2, 0, 1, 2, 2, 1, 2, 0, 0, 2, 1, 2, 2, 2, 2, 0, 2,
       2, 0, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 2, 1, 2, 1, 0, 1, 0, 0, 2, 1,
       0, 1, 2, 0, 1, 2, 0, 2], dtype=int64)

In [91]:
cohen_kappa_score(y_test,y_pred)

0.7622585438335809

In [92]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.84375